jobs:
  - name: rituraj-1-1-x
    type: manifest
    steps:
      - IN: box-nginx-1-1-x
        
  - name: runSh-job-x
    type: runSh
    steps:
      - IN: gitRepo-resource-x
        showBuildStatus: true
      - IN: rituraj-1-1-x
      - TASK:
        - script: echo 'start runSh hello'
        - script: printenv
    on_success:
      - script: echo "Hello from on_success"
    on_failure:
      - script: echo "Hello from on_failure"
      - script: echo ":("
    always:
      - script: echo "Hello from always"
      - script: echo ":|"
      
  - name: runSh-job-2-x
    type: runSh
    steps:
      - IN: gitRepo-resource-x
        showBuildStatus: true
      - IN: rituraj-1-1-x
      - TASK:
        - script: echo 'start runSh hello 2'
        - script: printenv
        
